### ISSUE TITLE
Static mode

### ISSUE THREAD

**Issue by oknozor** [oknozor/onagre#25]
Custom menu such as power menu is a common usage for app launcher, for instance [rofi-power-menu](https://github.com/jluttine/rofi-power-menu) provides a  handy way to manage system power with rofi. 

One way to do this would be to open onagre in "static" mode, i.e: loading predefined entries on start and not forwarding search requests to pop-launcher. This could be done mapping pop-launcher script mode to onagre config : 

```toml
[static.mode.session]
entries = ["Log out", "Restart", "Power off", "Suspend" ] # mapping to pop-launcher script name
theme = "session.toml"
``` 

with this defined we should be able to launch onagre like so : 
```shell
onagre -m session
```

Search should not filter out results, just change the selected line using some fuzzy matching, (maybe with [skim](https://github.com/lotabout/skim))
